mode: instruct  # or: instruct

name: anthony_cv

data:
  input_pdf: "docs/anthony_cv.pdf"
  data_dir: "data/anthony"
  entity: "Anthony Sun"
  doc_type: "CV"
  validation_split: 0.1
  min_length: 40
  text_mode: "columns"
  seed: 42

train:
  mode: instruct
  model_name: anthony-pretrain
  base_model_path: unsloth/Phi-3.5-mini-instruct
  max_seq_length: 2048
  seed: 42

instruct:
  ollama_model: mistral
  max_questions: 3
  delay: 0.5

export:
  convert_to_gguf: true
  gguf_output_dir: ollama/anthony