name: bible_kjv

data:
  mode: pretrain
  input_pdf: docs/bible_kjv.txt
  data_dir: "data/bible_kjv"
  entity: "Bible"
  doc_type: "scripture"  
  text_mode: "columns"
  chunk_size: 1500
  chunk_overlap: 200
  inject: 0

train:
  mode: pretrain
  model_name: bible_kjv
  data_dir: "data/bible_kjv"
  base_model_path: unsloth/Llama-3.2-3B-Instruct-bnb-4bit
  max_seq_length: 512    
  training_args:
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 4
    fp16: 1
    save_total_limit: 1
    learning_rate: 2e-5
    num_train_epochs: 2
    seed: 42

instruct:
  ollama_model: mistral
  max_questions: 3
  delay: 0.5

export:
  convert_to_gguf: true
  gguf_output_dir: ollama/anthony
